import type { Client, Invoice, Project } from '../types'

const now = new Date().toISOString()

export const seedClients: Client[] = [
  { id: 1, name: 'Estudio Nortex', contact: 'Laura García', email: 'laura@nortex.studio', totalBilled: 8400 },
  { id: 2, name: 'Vela Studio', contact: 'Carlos Ruiz', email: 'carlos@vela.studio', totalBilled: 6200 },
  { id: 3, name: 'Café Andino', contact: 'Elena Rostova', email: 'elena@cafeandino.co', totalBilled: 4500 },
  { id: 4, name: 'Otros clientes', contact: 'Varios', email: 'hola@chrono.app', totalBilled: 3800 },
]

export const seedProjects: Project[] = [
  {
    id: 1,
    title: 'Rediseño landing page',
    clientId: 1,
    clientName: 'Estudio Nortex',
    status: 'Pendiente',
    priority: 'Alta',
    color: 'violet',
    budget: 3200,
    deadline: '15 Sep, 2026',
    hoursTracked: 14400,
    hourlyRate: 50,
    createdAt: now,
    tasks: [
      { id: 1, text: 'Wireframes y wireflows', done: true },
      { id: 2, text: 'Prototipo Figma alta fidelidad', done: false },
      { id: 3, text: 'Revisión con cliente', done: false },
      { id: 4, text: 'Maquetación HTML/CSS', done: false },
      { id: 5, text: 'Optimizaciones de velocidad', done: false },
      { id: 6, text: 'Integración con CMS', done: false },
      { id: 7, text: 'Pruebas responsive', done: false },
      { id: 8, text: 'Despliegue final', done: false },
    ],
  },
  {
    id: 2,
    title: 'Auditoría SEO',
    clientId: 3,
    clientName: 'Café Andino',
    status: 'Pendiente',
    priority: 'Media',
    budget: 1500,
    deadline: '20 Sep, 2026',
    hoursTracked: 0,
    hourlyRate: 50,
    createdAt: now,
    tasks: [
      { id: 1, text: 'Análisis de palabras clave', done: false },
      { id: 2, text: 'Auditoría técnica On-Page', done: false },
      { id: 3, text: 'Revisión de backlinks', done: false },
      { id: 4, text: 'Optimización de Core Web Vitals', done: false },
      { id: 5, text: 'Entrega de informe', done: false },
    ],
  },
  {
    id: 3,
    title: 'App móvil de reservas',
    clientId: 2,
    clientName: 'Vela Studio',
    status: 'En Progreso',
    priority: 'Alta',
    color: 'blue',
    budget: 6800,
    deadline: '28 Sep, 2026',
    hoursTracked: 43200,
    hourlyRate: 50,
    createdAt: now,
    tasks: [
      { id: 1, text: 'Diseño UX/UI de flujos', done: true },
      { id: 2, text: 'Setup de React Native + Expo', done: true },
      { id: 3, text: 'Autenticación de usuarios', done: true },
      { id: 4, text: 'Conexión a API REST', done: true },
      { id: 5, text: 'Pasarela de pago', done: true },
      { id: 6, text: 'Notificaciones push', done: true },
      { id: 7, text: 'Testing en dispositivos Android', done: false },
      { id: 8, text: 'Testing en dispositivos iOS', done: false },
      { id: 9, text: 'Pruebas de carga', done: false },
      { id: 10, text: 'Publicación en TestFlight', done: false },
      { id: 11, text: 'Aprobación final', done: false },
    ],
  },
  {
    id: 4,
    title: 'Newsletter mensual',
    clientId: 1,
    clientName: 'Estudio Nortex',
    status: 'En Progreso',
    priority: 'Baja',
    budget: 850,
    deadline: '05 Sep, 2026',
    hoursTracked: 7200,
    hourlyRate: 50,
    createdAt: now,
    tasks: [
      { id: 1, text: 'Redacción de contenido', done: true },
      { id: 2, text: 'Diseño de plantilla Mailchimp', done: true },
      { id: 3, text: 'Envío de prueba', done: false },
      { id: 4, text: 'Programación de campaña', done: false },
      { id: 5, text: 'Reporte de aperturas y clics', done: false },
    ],
  },
  {
    id: 5,
    title: 'Identidad de marca',
    clientId: 3,
    clientName: 'Café Andino',
    status: 'En Revisión',
    priority: 'Media',
    color: 'pink',
    budget: 2400,
    deadline: '10 Sep, 2026',
    hoursTracked: 28800,
    hourlyRate: 50,
    createdAt: now,
    tasks: [
      { id: 1, text: 'Moodboard de conceptos', done: true },
      { id: 2, text: 'Diseño de logotipo', done: true },
      { id: 3, text: 'Paleta cromática y tipografías', done: true },
      { id: 4, text: 'Mockups de papelería', done: true },
      { id: 5, text: 'Guía de estilo de marca', done: true },
      { id: 6, text: 'Revisión final con cliente', done: true },
      { id: 7, text: 'Exportación de vectores en SVG/EPS', done: false },
    ],
  },
  {
    id: 6,
    title: 'Landing page V1',
    clientId: 2,
    clientName: 'Vela Studio',
    status: 'Completado',
    priority: 'Baja',
    budget: 1800,
    deadline: '25 Ago, 2026',
    hoursTracked: 21600,
    hourlyRate: 50,
    createdAt: now,
    tasks: [
      { id: 1, text: 'Estructuración HTML semántico', done: true },
      { id: 2, text: 'Estilos CSS modernos', done: true },
      { id: 3, text: 'Integración de formulario de contacto', done: true },
      { id: 4, text: 'Optimización SEO básica', done: true },
      { id: 5, text: 'Despliegue en servidor', done: true },
    ],
  },
  {
    id: 7,
    title: 'Facturación automatizada',
    clientId: 1,
    clientName: 'Estudio Nortex',
    status: 'Completado',
    priority: 'Alta',
    budget: 4100,
    deadline: '01 Sep, 2026',
    hoursTracked: 36000,
    hourlyRate: 50,
    createdAt: now,
    tasks: [
      { id: 1, text: 'Script de generación de PDFs', done: true },
      { id: 2, text: 'Webhooks de confirmación de pago', done: true },
      { id: 3, text: 'Recordatorios automáticos por correo', done: true },
      { id: 4, text: 'Integración con dashboard', done: true },
    ],
  },
]

export const seedInvoices: Invoice[] = [
  { id: 'INV-2026-004', number: 'INV-2026-004', clientId: 2, clientName: 'Vela Studio', amount: 620, date: '03 Sep 2026', dueDate: '15 Sep 2026', status: 'Pendiente' },
  { id: 'INV-2026-003', number: 'INV-2026-003', clientId: 3, clientName: 'Café Andino', amount: 980, date: '01 Sep 2026', dueDate: '14 Sep 2026', status: 'Pendiente' },
  { id: 'INV-2026-002', number: 'INV-2026-002', clientId: 1, clientName: 'Estudio Nortex', amount: 550, date: '28 Ago 2026', dueDate: '10 Sep 2026', status: 'Pendiente' },
  { id: 'INV-2026-001', number: 'INV-2026-001', clientId: 1, clientName: 'Estudio Nortex', amount: 1400, date: '15 Ago 2026', dueDate: '28 Ago 2026', status: 'Pagada' },
]